= Innovating through procurements at Barcelona City Council

== Background

Europe (Directive 2014/24/EU) is promoting strategic public procurement which ties together the concept of efficiency in public expenditure and the promotion of the common European social objectives established in the “European Commission communication Europe 2020, _A strategy for smart, sustainable_ _and inclusive growth.”_

Along these lines, last April, Barcelona City Council passed a Mayoral Decree on *sustainable public procurement* (S1/D/2017-1271, 24 April), which states that “Barcelona City Council promotes sustainable public procurement which includes social, environmental, ethical and innovation measures in the cause and purpose of the municipal contract and which guarantees the labour, social, and citizen’s rights of the people who execute the public contract and of the recipients or users of said contract.
Furthermore, said procurement should promote a local circular and sustainable economy, as well as foster the economic activity of local small, medium and micro- enterprises and, particularly, social enterprises”.

This decree also approved the social public procurement and environmental public procurement guides which have been the guidelines for sustainable public procurement at Barcelona City Council.

This *innovative public procurement* guide aims to complement the guidelines which have already been approved, and add innovation in connection to economic, social and environmental sustainability as a multiplying element which helps create employment and economic growth, strengthens social and environmental values, while also supporting innovative companies that solve citizens’ challenges.

This guide has been debated internally within city government and subsequently with citizen entities that represent economic, social and resident interests as part of the “Public Procurement Forum” established by Mayoral Resolution of 21 October 2016 as a space for citizen dialogue regarding public procurement.

== What is public procurement for innovation (PPI)?

Public procurement for innovation is a new way of contracting services and negotiating with the market in order to respond to needs that cannot be solved through ordinary processes.

It is using public money to buy what we need, while trying to spend that money strategically so as to reach our goals of improving and satisfying citizens’ needs, and strengthening innovation and sustainability.

This new approach to public procurement is designed to be a fundamental tool for the City Council to obtain solutions that are much better adapted to the real demands of society and to help companies be more competitive.
We hope to stimulate the creation of new local markets, new products, new production methods and new ways to organise or provide services.

How are we going to do that? In practice, PPI begins with an open definition of the challenges and needs to be addressed, and offers the market the opportunity to explain how the problem can be solved, whether with existing solutions or not.
These solutions must offer good value for money and consider the life cycle to calculate and determine costs.
This practice positions the City Council with a role beyond that of purchaser to become a partner in solving the challenge identified.

We must shift from public procurements with very detailed technical specifications and which are often awarded to the lowest bidder, to procurements that are based on the definition of challenges and innovative, sustainable solutions; this will often involve multiple players.
This new approach allows us to identify new ideas and innovative solutions that deliver efficiency.
A simple example would be to buy light instead of lampposts, or to buy hours of writing instead of pens.

Thus, the City Council is positioning itself as a driver of innovation in the market and a testing ground for its procurements by acquiring the results of research instead of subsidising pilot trials which often have difficulty scaling their impact.

Other key elements of PPI are risk, cost efficiency, collaboration between entities, and ensuring that benefits are shared.

.Main benefits of PPI:
TIP: *FOR CITIZENS* +
Improves public services by including innovative goods or services that better and more efficiently serve the needs of all city residents. +
*FOR INDUSTRY* +
Supports innovative companies and SMEs that promote the City Council’s values on social, environmental and technological matters, driving development and internationalisation, as they build off of access to the local public market as their first flagship customer. +
*FOR PUBLIC ADMINISTRATION* +
Promotes a cultural change within the Administration, shifting it towards more innovative practices and attaining economic and technical efficiency.

== Public procurement with strategic vision

The Europe 2020 strategy for smart, sustainable and inclusive growth promotes an economy based on knowledge and innovation, with a more effective use of resources, that is more competitive, with a high level of employment, and which supports social and territorial cohesion.
Directive 2014/24 indicates in its Second Recital that public procurement plays a key role in the Europe 2020 strategy.

___

*Under the European initiative Horizon 2020 initiative, funds have been made available so that the public and private sectors can reach sustainable growth and innovation goals.*
*In the 2014- 2020 period, the EU is planning to invest 70.2 billion euros.*

___

This is because government expenditure represent 20% of European GDP, making them an important economic agent with a great capacity to influence the market.

In fact, the European Union is actively promoting public procurement for innovation (PPI) as a public policy instrument.
In addition to offering funds to finance it, the EU has established new procedures that support innovation and encourage purchasing sectors to work differently, with a more strategic vision.

PPI aims to close the gap between social and citizen needs, administrative processes and the market.

Until now, governments have subsidised industry and research in order to develop new technologies and their applications.
However, these projects often do not advance beyond the pilot phase and lead to disillusionment in the industry, which loses confidence in the public sector as a driver of innovation.

This new approach to public procurement aims to bring innovation closer to the market, and turn the public sector into a customer and beneficiary of sustainable and innovative solutions that are more suited to its needs.

However this is not just a theory; there are good examples in sectors such as infrastructure and health where we are starting to see the objective results of applying this new procurement method, in which the public sector’s capacity for demand is the essential instrument for developing new markets and satisfying increasingly demanding and complex social needs.


== What role will Barcelona play?

In 2014 Barcelona was named the European Capital of Innovation.
That same year, the European Union passed the new public procurement Directives.
Europe is asking us to purchase innovative solutions to solve challenges that wouldn’t have an effective solution to our social and environmental issues in the 21st century without cutting edge technologies and research.

___

*Research and innovation, including ecological and social innovation, are among the main drivers of future growth and are a central part of the Europe 2020 strategy*

___

However, the European Commission’s vision of innovation is a linear process that starts with an idea, moves through different stages of maturity supported by technological centres, until finally reaching the market.

Other voices are bringing a broader vision to Europe, noting that the new approach to public procurement with strategic vision from the administrations generates innovation in and of itself.
Innovation is not necessarily the end result of a research project that starts with an idea, but rather can arise in a broader sense from all the players who, attracted by the opportunity to solve the challenges posed by the Administration (also called sophisticated demand), generate innovation.
Society as a whole creates innovation in the process of looking for solutions to the challenges posed.
Barcelona sees innovation as an end in itself and, at the same time, as a way to develop more social and environmental solutions.

The City Council would like to take advantage of its knowledge and that of the market so as to help solve the city’s challenges with new solutions.
This requires new skills for the people in charge of managing the public budget, new skills for technical municipal personnel, new legal procurement mechanisms and new, more agile methodologies in developing solutions for citizens.
It also requires new ways of explaining the challenges of the city and its citizens to the market and residents, thus facilitating shared, collaborative research and development for solutions.

Innovation must be used to serve the people and the common good.
The public sector becomes a promoter of innovative enterprise, innovating itself in terms of how it relates with the market and its procurement procedures.

The importance of price, which until now has been dominant, must become secondary.
Through planning, communication in the market of future invitations to tender, events, and dialogue with the market, new formulas must be designed that reward investment in Research, Development and Innovation by SMEs when that investment is aimed at creating growth and employment, or at protecting our social and environmental values.
Thus, we will ensure the market has confidence in a City Council that generates value and is a buyer, creating a local critical mass in the public and private sector that learns to purchase, sell and, above all, collaborate in a different way, promoting innovative solutions for the common good.

TIP: Barcelona is committed to innovation in the broader sense, and has decided to use its procurement potential to stimulate innovation that is aimed at solving the challenges of life in the city and to extend the impact of its social and environmental policies.

== Can we promote innovation in regular procurements?

The answer is yes, by including the option for variations and measures that encourage innovation in contracts and by modifying the procurement process (planning, prior consultations, etc.).

TIP: Barcelona proposes a broad definition of promoting innovation in its strategy.
 +
It sees public procurement for innovation (PPI) as public procurement which makes use of the innovative solutions (products, technologies, processes) that arise from the procurement process to promote a greater impact on sustainable and inclusive growth in society.
 +
Barcelona also encourages the inclusion of innovation in its regular procurements, with the same goals.

.We already have experience
TIP: The BCN Open Challenge meant that, for the first time, the City Council itself became the customer and purchaser of innovative solutions, closing the circle of “urban labs” and combining funding and the level of commitment of public procurement in the programme to solve challenges.
However, the BCN Open Challenge was also established with the desire to reach any individual, professional, company, or group that had an applicable innovative idea, regardless of their nature or experience, thereby ensuring opportunities for everyone with a capacity to innovate.
 +
For this reason, the nature of the companies chosen was very diverse.
This is a particular point of pride for us, as the winners included both already-formed small and medium enterprises as well as start-ups created expressly to participate in this call for proposals, a temporary joint venture, and even a technological centre, which demonstrates the capacity of this programme to promote new, innovative business forms and collaboration among businesses.
 +
_http://www.barcelonactiva.cat/barcelonactiva/es/novedades-y-prensa/novetats/2014/05/09/noticia112879.jsp_

== Who is this guide for?

This guide is:

[cols=",,",options="header",]
|===
|
*For everyone who works at Barcelona City Council, heads of areas and municipal bodies, individuals responsible for public procurement and technical municipal personnel.*
|
*For the private sector, companies and entities that supply or provide services to the City Council, whether now or in the future.*
|
*For citizens, as transparency in all strategic public procurement and innovation will be the common theme to all of our initiatives.*
|===

The guide invites all those who read it to view innovation as an essential element that is inseparable from and strengthens sustainable procurement, as is set out in the Mayoral Decree on sustainable public procurement (S1/D/2017-1271 of 24 April).
Article one of this Decree establishes the desire to boost social, environmental and innovation measures.
The decree establishes a guarantee for the labour, social, and citizen’s rights of the people who execute the public contract and of the recipients of said contract, and boosts actions for a circular economy and improving the economic activity of small and medium enterprises.

.Article 6. Innovation
TIP: 6.1. Article 2.1.22 of Directive 24/2014 on public procurement defines innovation as “the implementation of a new or significantly improved product, service or process, including but not limited to production, building or construction processes, a new marketing method, or a new organisational method in business practices, workplace organisation or external relations inter alia with the purpose of helping to solve societal challenges or to support the Europe 2020 strategy for smart, sustainable and inclusive growth...”.
 +
6.2. Barcelona City Council will drive public procurement processes for innovation with the aim of promoting research and the development of ideas and new technologies that will assist its work for citizens when said ideas and technologies are not available in the market.
 +
6.3. In general, when procuring works, goods and services, measures to strengthen innovation will be included through the establishment of functional technical specifications, award criteria that promote improvements articulated as innovation proposals or any other measure which promotes innovation related to developing economic, social and environmental sustainability.
 +
_Mayoral Decree on sustainable public procurement (S1/D/2017-1271 of 24 April)_
